### ISSUE TITLE
codec.SeekingDecoder passes on a broken Reader

### ISSUE THREAD

**Issue by jfreymuth** [zikichombo/codec#15]
`codec.SeekingDecoder` calls a codec's `SeekingDecoder` function with a `*brCloser`.
This struct implements `io.Reader` via a `bufio.Reader`, but also exposes the `Seek` method of the underlying Reader, so calls to `Read` after calls to `Seek` return wrong data.

Also, a codec's `Decoder` function is called with a struct that can be type asserted to an `io.Seeker`, but it's `Seek` method always panics, which is not technically a bug, but very inconvenient with the way my oggvorbis package works.

**Comment by wsc1** [comment]
Thanks for the comments.

I see how being castable to Seeker that only panics can be a problem.   will think of a way around it.  

For calls to read after seek, yes that's a bug.  Note also [this comment](https://github.com/zikichombo/codec/issues/3#issuecomment-419555634)

which recognises another bug in codec.Codec and proposes to use an interface in its place.

I can get a new codec.Codec in place in the next two days or so.  Could you help review the new version?

**Comment by wsc1** [comment]
[This PR](https://github.com/zikichombo/codec/pull/16) I hope will address the issues you brought up.
